version: '3.8'

services:
    php:
        container_name: 'php'
        build:
            context: .
            target: test
        env_file:
            - './.env'
            - './.env.local'
        volumes:
            - './:/var/www/html'
        restart: unless-stopped
        # command: ["tail", "-f", "/dev/null"]
        # command: ["/bin/sh","-c","cd /var/www/ && composer install"]
        # "/usr/local/bin/composer", "install"
