version: '3.8'

services:
    php:
        container_name: 'php'
        build:
            context: .
            target: dev
        env_file:
            - './.env'
            - './.env.local'
        volumes:
            - './:/var/www/html'
        restart: unless-stopped
        # command: ["tail", "-f", "/dev/null"]
        # command: ["/bin/sh","-c","cd /var/www/ && composer install"]
        # "/usr/local/bin/composer", "install"
        # aws ecs register-task-definition --cli-input-json file://aws-task-definition.json
        # aws ecs run-task --cluster test --task-definition app:1 --count 1 --launch-type FARGATE --network-configuration "awsvpcConfiguration={subnets=[subnet-06701da3a55f3cde7],securityGroups=[sg-0b36fcc6a89245fc8]}"
